In [2]:
import pandas as pd
University=pd.read_csv('University.csv')
print(University)

     Grade Institution  Completionyear
0    First  Strathmore            2010
1    First  Strathmore            2022
2   Second  Strathmore            2023
3   Second  Strathmore            2015
4   Second         UOE            2014
5   Second        USIU            2021
6   Second        USIU            2022
7   Second         UON            2023
8     Pass         Moi            2015
9     Pass         UON            2014
10    Pass        USIU            2021
11    Pass        USIU            2014
12   First       UNISA            2010
13  Second       UNISA            2022
14  Second       UNISA            2023


In [3]:
import pandas as pd
University=pd.read_csv('University.csv')
uniquecolumns=University[['Grade','Institution']]
print(uniquecolumns)

     Grade Institution
0    First  Strathmore
1    First  Strathmore
2   Second  Strathmore
3   Second  Strathmore
4   Second         UOE
5   Second        USIU
6   Second        USIU
7   Second         UON
8     Pass         Moi
9     Pass         UON
10    Pass        USIU
11    Pass        USIU
12   First       UNISA
13  Second       UNISA
14  Second       UNISA


In [4]:
University=pd.read_csv('University.csv')
uniquecolumns=University[['Institution','Completionyear']]
print(uniquecolumns)

   Institution  Completionyear
0   Strathmore            2010
1   Strathmore            2022
2   Strathmore            2023
3   Strathmore            2015
4          UOE            2014
5         USIU            2021
6         USIU            2022
7          UON            2023
8          Moi            2015
9          UON            2014
10        USIU            2021
11        USIU            2014
12       UNISA            2010
13       UNISA            2022
14       UNISA            2023


In [11]:
import pandas as pd
University=pd.read_csv('University.csv')
strathmorevalues=University['Institution'].where(University['Institution']=='Strathmore')
print(strathmorevalues)

0     Strathmore
1     Strathmore
2     Strathmore
3     Strathmore
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
Name: Institution, dtype: object


In [19]:
#second values of UNISA
secondgradevalues = University['Grade'].where(University['Grade']=='Second')
secondgradevalues

0        NaN
1        NaN
2     Second
3     Second
4     Second
5     Second
6     Second
7     Second
8        NaN
9        NaN
10       NaN
11       NaN
12       NaN
13    Second
14    Second
Name: Grade, dtype: object

In [17]:
valuepass= University['Grade'].where(
    (University['Grade']=='Pass') & (University['Institution']=='USIU')
)
print(valuepass)

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
10    Pass
11    Pass
12     NaN
13     NaN
14     NaN
Name: Grade, dtype: object


In [1]:
import pandas as pd
feepaid=pd.read_csv('feepaid.csv')
print(feepaid)

   CustomerNo CustomerName      City  Feespaid
0      YT6998       Benard  Pretoria     500.0
1      RF2344      Maurice  Pretoria     564.0
2      RY5643       Juliet   Kampala     354.0
3      GH4563         Noel   Kampala     456.0
4      RT8976      Leonard    Durban     457.0
5      LK4356       Hellen  Pretoria     678.0
6      LK4356       Hellen  Pretoria     678.0
7      345678      Derrick   Kampala     897.0
8      RY5643     Beatrice   Mombasa     876.0
9      GH4563        Grace   Mombasa     457.0
10     RT8976       Reagan    Durban       NaN
11     LK4356       Benard   Mombasa     298.0
12     YT6998       Juliet  Pretoria     675.0
13     345678         Noel   Kampala     745.0
14     RY5643      Leonard  Pretoria     908.0
15     GH4563      Vincent   Kampala     786.0


In [2]:
import pandas as pd
cleaning=pd.read_csv('feepaid.csv')
newcleaning=cleaning.dropna()
print(newcleaning)

   CustomerNo CustomerName      City  Feespaid
0      YT6998       Benard  Pretoria     500.0
1      RF2344      Maurice  Pretoria     564.0
2      RY5643       Juliet   Kampala     354.0
3      GH4563         Noel   Kampala     456.0
4      RT8976      Leonard    Durban     457.0
5      LK4356       Hellen  Pretoria     678.0
6      LK4356       Hellen  Pretoria     678.0
7      345678      Derrick   Kampala     897.0
8      RY5643     Beatrice   Mombasa     876.0
9      GH4563        Grace   Mombasa     457.0
11     LK4356       Benard   Mombasa     298.0
12     YT6998       Juliet  Pretoria     675.0
13     345678         Noel   Kampala     745.0
14     RY5643      Leonard  Pretoria     908.0
15     GH4563      Vincent   Kampala     786.0


In [7]:
newcleaning.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [10]:
newcleaning

CustomerNo CustomerName      City  Feespaid
0      YT6998       Benard  Pretoria     500.0
1      RF2344      Maurice  Pretoria     564.0
2      RY5643       Juliet   Kampala     354.0
3      GH4563         Noel   Kampala     456.0
4      RT8976      Leonard    Durban     457.0
5      LK4356       Hellen  Pretoria     678.0
6      LK4356       Hellen  Pretoria     678.0
7      345678      Derrick   Kampala     897.0
8      RY5643     Beatrice   Mombasa     876.0
9      GH4563        Grace   Mombasa     457.0
11     LK4356       Benard   Mombasa     298.0
12     YT6998       Juliet  Pretoria     675.0
13     345678         Noel   Kampala     745.0
14     RY5643      Leonard  Pretoria     908.0
15     GH4563      Vincent   Kampala     786.0

In [37]:
newcleaning.drop_duplicates(inplace = True)
print(newcleaning)

   CustomerNo CustomerName      City  Feespaid
0      YT6998       Benard  Pretoria     500.0
1      RF2344      Maurice  Pretoria     564.0
2      RY5643       Juliet   Kampala     354.0
3      GH4563         Noel   Kampala     456.0
4      RT8976      Leonard    Durban     457.0
5      LK4356       Hellen  Pretoria     678.0
7      345678      Derrick   Kampala     897.0
8      RY5643     Beatrice   Mombasa     876.0
9      GH4563        Grace   Mombasa     457.0
11     LK4356       Benard   Mombasa     298.0
12     YT6998       Juliet  Pretoria     675.0
13     345678         Noel   Kampala     745.0
14     RY5643      Leonard  Pretoria     908.0
15     GH4563      Vincent   Kampala     786.0


C:\Users\Administrator\AppData\Local\Temp\ipykernel_16656\508438619.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newcleaning.drop_duplicates(inplace = True)


In [18]:
newcleaning

CustomerNo CustomerName      City  Feespaid
0      YT6998       Benard  Pretoria     500.0
1      RF2344      Maurice  Pretoria     564.0
2      RY5643       Juliet   Kampala     354.0
3      GH4563         Noel   Kampala     456.0
4      RT8976      Leonard    Durban     457.0
5      LK4356       Hellen  Pretoria     678.0
7      345678      Derrick   Kampala     897.0
8      RY5643     Beatrice   Mombasa     876.0
9      GH4563        Grace   Mombasa     457.0
11     LK4356       Benard   Mombasa     298.0
12     YT6998       Juliet  Pretoria     675.0
13     345678         Noel   Kampala     745.0
14     RY5643      Leonard  Pretoria     908.0
15     GH4563      Vincent   Kampala     786.0

In [19]:
import pandas as pd
Country=pd.read_csv('Country.csv')
print(Country)

    EmployeeID EmployeeFname  Gender   Country  Salary
0        201.0          Anne  Female     Kenya   40000
1        203.0         Alice  Female    Uganda   60000
2        204.0        Andrew    Male   Burundi   70000
3        205.0           Job    Male     Kenya   87000
4        206.0       Vincent    Male     Kenya   45000
5        208.0          Ayub    Male    Uganda   56000
6        209.0        Joseph    Male  Tanzania   64000
7        210.0       Barrack    Male  Tanzania   60000
8        201.0          Anne  Female     Kenya   40000
9        206.0       Vincent    Male     Kenya   45000
10         NaN        Andrew    Male   Burundi   70000
11       215.0        Victor    Male  Tanzania   89000


In [30]:
Country.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
10    False
11    False
dtype: bool

In [20]:
Country.dropna
print(Country)

    EmployeeID EmployeeFname  Gender   Country  Salary
0        201.0          Anne  Female     Kenya   40000
1        203.0         Alice  Female    Uganda   60000
2        204.0        Andrew    Male   Burundi   70000
3        205.0           Job    Male     Kenya   87000
4        206.0       Vincent    Male     Kenya   45000
5        208.0          Ayub    Male    Uganda   56000
6        209.0        Joseph    Male  Tanzania   64000
7        210.0       Barrack    Male  Tanzania   60000
8        201.0          Anne  Female     Kenya   40000
9        206.0       Vincent    Male     Kenya   45000
10         NaN        Andrew    Male   Burundi   70000
11       215.0        Victor    Male  Tanzania   89000


In [29]:
Country.drop_duplicates(inplace = True)
print(Country)

    EmployeeID EmployeeFname  Gender   Country  Salary
0        201.0          Anne  Female     Kenya   40000
1        203.0         Alice  Female    Uganda   60000
2        204.0        Andrew    Male   Burundi   70000
3        205.0           Job    Male     Kenya   87000
4        206.0       Vincent    Male     Kenya   45000
5        208.0          Ayub    Male    Uganda   56000
6        209.0        Joseph    Male  Tanzania   64000
7        210.0       Barrack    Male  Tanzania   60000
10         NaN        Andrew    Male   Burundi   70000
11       215.0        Victor    Male  Tanzania   89000


In [31]:
salarytotal=Country['Salary'].sum()
print('The total salary is:')
print(salarytotal)

The total salary is:
641000


In [2]:
import pandas as pd
University=pd.read_csv('University.csv')
print(University)

     Grade Institution  Completionyear
0    First  Strathmore            2010
1    First  Strathmore            2022
2   Second  Strathmore            2023
3   Second  Strathmore            2015
4   Second         UOE            2014
5   Second        USIU            2021
6   Second        USIU            2022
7   Second         UON            2023
8     Pass         Moi            2015
9     Pass         UON            2014
10    Pass        USIU            2021
11    Pass        USIU            2014
12   First       UNISA            2010
13  Second       UNISA            2022
14  Second       UNISA            2023


In [3]:
import pandas as pd
from sklearn import preprocessing
University=pd.read_csv('University.csv')
encode=preprocessing.LabelEncoder()
EncodedUniversity=University.apply(preprocessing.LabelEncoder().fit_transform)
print('Encoded data is:\n',EncodedUniversity)

Encoded data is:
     Grade  Institution  Completionyear
0       0            1               0
1       0            1               4
2       2            1               5
3       2            1               2
4       2            3               1
5       2            5               3
6       2            5               4
7       2            4               5
8       1            0               2
9       1            4               1
10      1            5               3
11      1            5               1
12      0            2               0
13      2            2               4
14      2            2               5


In [41]:
#splitting the data
import pandas as pd
from numpy import array
slicing=array([11,22,33,44,55])
print(slicing[0:1])

[11]


In [40]:
import pandas as pd
from numpy import array
slicing=array([11,22,33,44,55])
print(slicing[1:2])

[22]


In [42]:
print(slicing[-2:])

[44 55]


In [43]:
print(slicing[-3:])

[33 44 55]


In [4]:
numericarray=EncodedUniversity.values
print(numericarray)

[[0 1 0]
 [0 1 4]
 [2 1 5]
 [2 1 2]
 [2 3 1]
 [2 5 3]
 [2 5 4]
 [2 4 5]
 [1 0 2]
 [1 4 1]
 [1 5 3]
 [1 5 1]
 [0 2 0]
 [2 2 4]
 [2 2 5]]


In [5]:
split=8
TrainingSample,TestSample=numericarray[:split,:],numericarray[split:,:]
print('Training Sample:\n',TrainingSample)
print('\nTest Sample:\n',TestSample)

Training Sample:
 [[0 1 0]
 [0 1 4]
 [2 1 5]
 [2 1 2]
 [2 3 1]
 [2 5 3]
 [2 5 4]
 [2 4 5]]

Test Sample:
 [[1 0 2]
 [1 4 1]
 [1 5 3]
 [1 5 1]
 [0 2 0]
 [2 2 4]
 [2 2 5]]


In [11]:
#splitting data into input and output attributes
X_attributes_trainingsample=TrainingSample[:,0:-1]
Y_attributes_trainingsample=TrainingSample[:,-1]
print('X attributes:\n',X_attributes_trainingsample)
print('\nY attribute:\n',Y_attributes_trainingsample)

X attributes:
 [[0 1]
 [0 1]
 [2 1]
 [2 1]
 [2 3]
 [2 5]
 [2 5]
 [2 4]]

Y attribute:
 [0 4 5 2 1 3 4 5]


In [14]:
from numpy import set_printoptions
#Normalize the dataset
normalized_X_attributes=preprocessing.normalize(X_attributes_trainingsample)
#set print option
set_printoptions(precision=3)
print(normalized_X_attributes)

[[0.    1.   ]
 [0.    1.   ]
 [0.894 0.447]
 [0.894 0.447]
 [0.555 0.832]
 [0.371 0.928]
 [0.371 0.928]
 [0.447 0.894]]
